export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const AUTH_SYSTEM_ERROR = "LOGIN_SYSTEM_ERROR"
export const AUTH_LOADING = "AUTH_LOADING"
export const USER_LOGOUT = 'USER_LOGOUT'

export const SEARCH_DEFAULT = 'SEARCH_DEFAULT'
export const SEARCH_BOX_FALSE = 'SEARCH_BOX_FALSE'
export const SEARCH_BOX_DATA = 'SEARCH_BOX_DATA'

export const ADD_TO_CARD = 'ADD_TO_CARD'
export const ADD_ON_LOGOUT = 'ADD__ON_LOGOUT'